# Site settings
title: Tanner Geo Blog
email: biolsurfer85@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tanner GEO Blog contains guides, snippets, and examples of building applications.
  I am a science and geo geek, but love programming and building just about anything.
<<<<<<< HEAD
#baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "http://tannerjt.github.io/geotanner/" # the base hostname & protocol for your site
highlighter: pygments
repository: https://github.com/tannerjt/geotanner

=======
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
>>>>>>> e84d68aff1bc7ca4105be83c025ea815fb6fb844
#twitter_username: 
github_username:  tannerjt

# Build settings
markdown: kramdown
